CLI 'init' command fix
CESARBR/knot-cloud pull request #23
Opened 2020-01-10 20:45 UTC by esdrasjnr

(Thanks for sending a pull request! Please fill out the blanks below.)

What does this implement/fix? Explain your changes.
---------------------------------------------------
Fix command init for knot-cloud cli:
- Fix path in copy stacks folder
- Fix path used to clone the repositories

Does this close any currently open issues?
------------------------------------------
fix#20

Any relevant logs, error output, etc?
-------------------------------------
(If it’s long, please paste to https://pastebin.com/ and insert the link here.)

Any other comments?
-------------------
...

Where has this been tested?
---------------------------
(Describe your environment setup here.)

Ubuntu 18.04.3
NPM v6.13.6
NodeJS v12.13.1

(Add more information here if needed.)

2020-01-20 18:23 UTC, netoax requested changes

2020-01-20 18:23 UTC, joaoaneto commented on src/cmds/stack/setup.js
> +  const initPath = args.path || '';
What do you think about rename `initPath` to `path`?

2020-01-20 21:39 UTC, joaoaneto commented on src/cmds/stack/setup.js
> +  const initPath = args.path || '';
I noticed `path` is the name of the package you're using. Sorry!

2020-01-21 13:51 UTC, netoax requested changes
_753b4f36da0b34af1ebc73ddf226cb938a99368b_

"Fix knot-cloud init command when there is no path **argument**. **The
repositories paths had a wrong reference.**"

_98eae4fc44428dcfed1a6a64d68e2af74c538150_

"Fix error while copying dev stack files. The copy command was **referring**
to an inexisting path."

2020-01-21 14:08 UTC, esdrasjnr commented
> _[753b4f3](https://github.com/CESARBR/knot-cloud/commit/753b4f36da0b34af1ebc73ddf226cb938a99368b)_
> 
> "Fix knot-cloud init command when there is no path **argument**. **The repositories paths had a wrong reference.**"
> 
> _[98eae4f](https://github.com/CESARBR/knot-cloud/commit/98eae4fc44428dcfed1a6a64d68e2af74c538150)_
> 
> "Fix error while copying dev stack files. The copy command was **referring**
> to an inexisting path."

2020-01-21 14:10 UTC, esdrasjnr commented
> _[753b4f3](https://github.com/CESARBR/knot-cloud/commit/753b4f36da0b34af1ebc73ddf226cb938a99368b)_
> 
> "Fix knot-cloud init command when there is no path **argument**. **The repositories paths had a wrong reference.**"
> 
> _[98eae4f](https://github.com/CESARBR/knot-cloud/commit/98eae4fc44428dcfed1a6a64d68e2af74c538150)_
> 
> "Fix error while copying dev stack files. The copy command was **referring**
> to an inexisting path."

@joaoaneto Done!

2020-01-21 14:34 UTC, netoax approved these changes

2020-01-21 14:34 UTC, merged